{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "095ae6d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: google-cloud-aiplatform[adk,agent_engines] in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.95.1)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (2.25.0)\n",
      "Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (2.40.2)\n",
      "Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.26.1)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (6.31.1)\n",
      "Requirement already satisfied: packaging>=14.3 in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (24.2)\n",
      "Requirement already satisfied: google-cloud-storage<3.0.0,>=1.32.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (2.19.0)\n",
      "Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (3.34.0)\n",
      "Requirement already satisfied: google-cloud-resource-manager<3.0.0,>=1.3.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.14.2)\n",
      "Requirement already satisfied: shapely<3.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (2.1.1)\n",
      "Requirement already satisfied: google-genai<2.0.0,>=1.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.18.0)\n",
      "Requirement already satisfied: pydantic<3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (2.11.5)\n",
      "Requirement already satisfied: typing-extensions in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (4.12.2)\n",
      "Requirement already satisfied: docstring-parser<1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (0.16)\n",
      "Requirement already satisfied: google-adk<2.0.0,>=1.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.1.1)\n",
      "Collecting cloudpickle<4.0,>=3.0 (from google-cloud-aiplatform[adk,agent_engines])\n",
      "  Downloading cloudpickle-3.1.1-py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: google-cloud-trace<2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.16.1)\n",
      "Collecting google-cloud-logging<4 (from google-cloud-aiplatform[adk,agent_engines])\n",
      "  Downloading google_cloud_logging-3.12.1-py2.py3-none-any.whl.metadata (5.0 kB)\n",
      "Requirement already satisfied: opentelemetry-sdk<2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.33.1)\n",
      "Requirement already satisfied: opentelemetry-exporter-gcp-trace<2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-aiplatform[adk,agent_engines]) (1.9.0)\n",
      "Requirement already satisfied: authlib>=1.5.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.6.0)\n",
      "Requirement already satisfied: click>=8.1.8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (8.2.1)\n",
      "Requirement already satisfied: fastapi>=0.115.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.115.12)\n",
      "Requirement already satisfied: google-api-python-client>=2.157.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.171.0)\n",
      "Requirement already satisfied: google-cloud-secret-manager>=2.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.23.3)\n",
      "Requirement already satisfied: google-cloud-speech>=2.30.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.32.0)\n",
      "Requirement already satisfied: graphviz>=0.20.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.20.3)\n",
      "Requirement already satisfied: mcp>=1.5.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.9.2)\n",
      "Requirement already satisfied: opentelemetry-api>=1.31.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.33.1)\n",
      "Requirement already satisfied: python-dotenv>=1.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.1.0)\n",
      "Requirement already satisfied: PyYAML>=6.0.2 in /home/codespace/.local/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (6.0.2)\n",
      "Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.0.41)\n",
      "Requirement already satisfied: tzlocal>=5.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (5.3.1)\n",
      "Requirement already satisfied: uvicorn>=0.34.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.34.3)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (1.70.0)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.18.0 in /home/codespace/.local/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (2.32.3)\n",
      "Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (1.72.1)\n",
      "Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (1.72.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-aiplatform[adk,agent_engines]) (5.5.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-aiplatform[adk,agent_engines]) (0.4.2)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-aiplatform[adk,agent_engines]) (4.9.1)\n",
      "Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform[adk,agent_engines]) (2.4.3)\n",
      "Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform[adk,agent_engines]) (2.7.2)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform[adk,agent_engines]) (2.9.0.post0)\n",
      "Collecting google-cloud-appengine-logging<2.0.0,>=0.1.3 (from google-cloud-logging<4->google-cloud-aiplatform[adk,agent_engines])\n",
      "  Downloading google_cloud_appengine_logging-1.6.1-py3-none-any.whl.metadata (9.7 kB)\n",
      "Collecting google-cloud-audit-log<1.0.0,>=0.3.1 (from google-cloud-logging<4->google-cloud-aiplatform[adk,agent_engines])\n",
      "  Downloading google_cloud_audit_log-0.3.2-py3-none-any.whl.metadata (9.0 kB)\n",
      "Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.12.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-logging<4->google-cloud-aiplatform[adk,agent_engines]) (0.14.2)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-cloud-storage<3.0.0,>=1.32.0->google-cloud-aiplatform[adk,agent_engines]) (1.7.1)\n",
      "Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /home/codespace/.local/lib/python3.12/site-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (4.9.0)\n",
      "Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /home/codespace/.local/lib/python3.12/site-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.28.1)\n",
      "Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (15.0.1)\n",
      "Requirement already satisfied: opentelemetry-resourcedetector-gcp==1.*,>=1.5.0dev0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from opentelemetry-exporter-gcp-trace<2->google-cloud-aiplatform[adk,agent_engines]) (1.9.0a0)\n",
      "Requirement already satisfied: opentelemetry-semantic-conventions==0.54b1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from opentelemetry-sdk<2->google-cloud-aiplatform[adk,agent_engines]) (0.54b1)\n",
      "Requirement already satisfied: deprecated>=1.2.6 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from opentelemetry-api>=1.31.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.2.18)\n",
      "Requirement already satisfied: importlib-metadata<8.7.0,>=6.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from opentelemetry-api>=1.31.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (8.6.1)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pydantic<3->google-cloud-aiplatform[adk,agent_engines]) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pydantic<3->google-cloud-aiplatform[adk,agent_engines]) (2.33.2)\n",
      "Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pydantic<3->google-cloud-aiplatform[adk,agent_engines]) (0.4.1)\n",
      "Requirement already satisfied: numpy>=1.21 in /home/codespace/.local/lib/python3.12/site-packages (from shapely<3.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.2.4)\n",
      "Requirement already satisfied: idna>=2.8 in /home/codespace/.local/lib/python3.12/site-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (3.10)\n",
      "Requirement already satisfied: sniffio>=1.1 in /home/codespace/.local/lib/python3.12/site-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.3.1)\n",
      "Requirement already satisfied: cryptography in /usr/local/python/3.12.1/lib/python3.12/site-packages (from authlib>=1.5.1->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (45.0.3)\n",
      "Requirement already satisfied: starlette<0.47.0,>=0.40.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from fastapi>=0.115.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.46.2)\n",
      "Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-python-client>=2.157.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.22.0)\n",
      "Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-python-client>=2.157.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.2.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from google-api-python-client>=2.157.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (4.2.0)\n",
      "Requirement already satisfied: certifi in /home/codespace/.local/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2025.1.31)\n",
      "Requirement already satisfied: httpcore==1.* in /home/codespace/.local/lib/python3.12/site-packages (from httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.0.7)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/codespace/.local/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.14.0)\n",
      "Requirement already satisfied: httpx-sse>=0.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mcp>=1.5.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.4.0)\n",
      "Requirement already satisfied: pydantic-settings>=2.5.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mcp>=1.5.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.9.1)\n",
      "Requirement already satisfied: python-multipart>=0.0.9 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mcp>=1.5.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (0.0.20)\n",
      "Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from mcp>=1.5.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.3.6)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-aiplatform[adk,agent_engines]) (0.6.1)\n",
      "Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery!=3.20.0,<4.0.0,>=1.15.0->google-cloud-aiplatform[adk,agent_engines]) (1.17.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (3.4.1)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0,>=1.34.1->google-cloud-aiplatform[adk,agent_engines]) (2.3.0)\n",
      "Requirement already satisfied: greenlet>=1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from sqlalchemy>=2.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (3.2.2)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api>=1.31.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.17.2)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /home/codespace/.local/lib/python3.12/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client>=2.157.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (3.2.1)\n",
      "Requirement already satisfied: zipp>=3.20 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from importlib-metadata<8.7.0,>=6.0->opentelemetry-api>=1.31.0->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (3.22.0)\n",
      "Requirement already satisfied: cffi>=1.14 in /home/codespace/.local/lib/python3.12/site-packages (from cryptography->authlib>=1.5.1->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (1.17.1)\n",
      "Requirement already satisfied: pycparser in /home/codespace/.local/lib/python3.12/site-packages (from cffi>=1.14->cryptography->authlib>=1.5.1->google-adk<2.0.0,>=1.0.0->google-cloud-aiplatform[adk,agent_engines]) (2.22)\n",
      "Downloading cloudpickle-3.1.1-py3-none-any.whl (20 kB)\n",
      "Downloading google_cloud_logging-3.12.1-py2.py3-none-any.whl (229 kB)\n",
      "Downloading google_cloud_appengine_logging-1.6.1-py3-none-any.whl (16 kB)\n",
      "Downloading google_cloud_audit_log-0.3.2-py3-none-any.whl (32 kB)\n",
      "Installing collected packages: cloudpickle, google-cloud-audit-log, google-cloud-appengine-logging, google-cloud-logging\n",
      "Successfully installed cloudpickle-3.1.1 google-cloud-appengine-logging-1.6.1 google-cloud-audit-log-0.3.2 google-cloud-logging-3.12.1\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.1.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython3 -m pip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "! pip install google-cloud-aiplatform[adk,agent_engines]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "28f92250",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "agent_engine has none of the following callable methods: `query`, `async_query`, `stream_query`, `async_stream_query` or `register_operations`.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mTypeError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 4\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01magents\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mhuman\u001b[39;00m\u001b[34;01m.\u001b[39;00m\u001b[34;01mmain_agent\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mroot_agent\u001b[39;00m\n\u001b[32m      2\u001b[39m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mvertexai\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m agent_engines\n\u001b[32m----> \u001b[39m\u001b[32m4\u001b[39m remote_app = \u001b[43magent_engines\u001b[49m\u001b[43m.\u001b[49m\u001b[43mcreate\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m      5\u001b[39m \u001b[43m    \u001b[49m\u001b[43magent_engine\u001b[49m\u001b[43m=\u001b[49m\u001b[43mroot_agent\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m      6\u001b[39m \u001b[43m    \u001b[49m\u001b[43mrequirements\u001b[49m\u001b[43m=\u001b[49m\u001b[43m[\u001b[49m\n\u001b[32m      7\u001b[39m \u001b[43m        \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mgoogle-cloud-aiplatform[adk,agent_engines]\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m      8\u001b[39m \u001b[43m    \u001b[49m\u001b[43m]\u001b[49m\n\u001b[32m      9\u001b[39m \u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.python/current/lib/python3.12/site-packages/vertexai/agent_engines/__init__.py:148\u001b[39m, in \u001b[36mcreate\u001b[39m\u001b[34m(agent_engine, requirements, display_name, description, gcs_dir_name, extra_packages, env_vars)\u001b[39m\n\u001b[32m     62\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mcreate\u001b[39m(\n\u001b[32m     63\u001b[39m     agent_engine: Optional[Union[Queryable, OperationRegistrable]] = \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[32m     64\u001b[39m     *,\n\u001b[32m   (...)\u001b[39m\u001b[32m     72\u001b[39m     ] = \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[32m     73\u001b[39m ) -> AgentEngine:\n\u001b[32m     74\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Creates a new Agent Engine.\u001b[39;00m\n\u001b[32m     75\u001b[39m \n\u001b[32m     76\u001b[39m \u001b[33;03m    The Agent Engine will be an instance of the `agent_engine` that\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    146\u001b[39m \u001b[33;03m        nonexistent file.\u001b[39;00m\n\u001b[32m    147\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m148\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mAgentEngine\u001b[49m\u001b[43m.\u001b[49m\u001b[43mcreate\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    149\u001b[39m \u001b[43m        \u001b[49m\u001b[43magent_engine\u001b[49m\u001b[43m=\u001b[49m\u001b[43magent_engine\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    150\u001b[39m \u001b[43m        \u001b[49m\u001b[43mrequirements\u001b[49m\u001b[43m=\u001b[49m\u001b[43mrequirements\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    151\u001b[39m \u001b[43m        \u001b[49m\u001b[43mdisplay_name\u001b[49m\u001b[43m=\u001b[49m\u001b[43mdisplay_name\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    152\u001b[39m \u001b[43m        \u001b[49m\u001b[43mdescription\u001b[49m\u001b[43m=\u001b[49m\u001b[43mdescription\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    153\u001b[39m \u001b[43m        \u001b[49m\u001b[43mgcs_dir_name\u001b[49m\u001b[43m=\u001b[49m\u001b[43mgcs_dir_name\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    154\u001b[39m \u001b[43m        \u001b[49m\u001b[43mextra_packages\u001b[49m\u001b[43m=\u001b[49m\u001b[43mextra_packages\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    155\u001b[39m \u001b[43m        \u001b[49m\u001b[43menv_vars\u001b[49m\u001b[43m=\u001b[49m\u001b[43menv_vars\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    156\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.python/current/lib/python3.12/site-packages/vertexai/agent_engines/_agent_engines.py:395\u001b[39m, in \u001b[36mAgentEngine.create\u001b[39m\u001b[34m(cls, agent_engine, requirements, display_name, description, gcs_dir_name, extra_packages, env_vars)\u001b[39m\n\u001b[32m    393\u001b[39m staging_bucket = initializer.global_config.staging_bucket\n\u001b[32m    394\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m agent_engine \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m395\u001b[39m     agent_engine = \u001b[43m_validate_agent_engine_or_raise\u001b[49m\u001b[43m(\u001b[49m\u001b[43magent_engine\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    396\u001b[39m     _validate_staging_bucket_or_raise(staging_bucket)\n\u001b[32m    397\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m agent_engine \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/.python/current/lib/python3.12/site-packages/vertexai/agent_engines/_agent_engines.py:783\u001b[39m, in \u001b[36m_validate_agent_engine_or_raise\u001b[39m\u001b[34m(agent_engine)\u001b[39m\n\u001b[32m    772\u001b[39m is_operation_registrable = \u001b[38;5;28misinstance\u001b[39m(\n\u001b[32m    773\u001b[39m     agent_engine, OperationRegistrable\n\u001b[32m    774\u001b[39m ) \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(agent_engine.register_operations)\n\u001b[32m    776\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m (\n\u001b[32m    777\u001b[39m     is_queryable\n\u001b[32m    778\u001b[39m     \u001b[38;5;129;01mor\u001b[39;00m is_async_queryable\n\u001b[32m   (...)\u001b[39m\u001b[32m    781\u001b[39m     \u001b[38;5;129;01mor\u001b[39;00m is_async_stream_queryable\n\u001b[32m    782\u001b[39m ):\n\u001b[32m--> \u001b[39m\u001b[32m783\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[32m    784\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33magent_engine has none of the following callable methods: \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    785\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33m`query`, `async_query`, `stream_query`, `async_stream_query` or \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    786\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33m`register_operations`.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    787\u001b[39m     )\n\u001b[32m    789\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m is_queryable:\n\u001b[32m    790\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[31mTypeError\u001b[39m: agent_engine has none of the following callable methods: `query`, `async_query`, `stream_query`, `async_stream_query` or `register_operations`."
     ]
    }
   ],
   "source": [
    "import agents.human.main_agent as root_agent\n",
    "from vertexai import agent_engines\n",
    "\n",
    "remote_app = agent_engines.create(\n",
    "    agent_engine=root_agent,\n",
    "    requirements=[\n",
    "        \"google-cloud-aiplatform[adk,agent_engines]\",\n",
    "    ]\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
